// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.JobPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobPosts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "We are seeking a talented Software Engineer with 3+ years of experience in developing scalable web applications. The ideal candidate should have strong proficiency in C# and .NET Core, experience with RESTful APIs, and familiarity with cloud platforms such as Azure or AWS. Knowledge of modern frontend frameworks (React, Angular, or Vue.js) is a plus. You'll be working on cutting-edge projects in a collaborative, agile environment.",
                            Title = "Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Join our data science team! We're looking for a Data Scientist with 2+ years of experience in machine learning and statistical analysis. The ideal candidate should be proficient in Python, R, or Julia, and have hands-on experience with popular ML libraries such as TensorFlow or PyTorch. Strong skills in data visualization and the ability to communicate complex findings to non-technical stakeholders are essential. Experience with big data technologies like Hadoop or Spark is a plus.",
                            Title = "Data Scientist"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "We're seeking a skilled Frontend Developer with expertise in React and TypeScript. The ideal candidate should have a strong understanding of modern web technologies, including HTML5, CSS3, and JavaScript ES6+. Experience with state management libraries (Redux, MobX) and testing frameworks (Jest, React Testing Library) is required. You'll be responsible for creating responsive, accessible, and performant user interfaces for our web applications. Knowledge of UX/UI principles and experience with design tools like Figma is a plus.",
                            Title = "Frontend Developer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "We're looking for a DevOps Engineer familiar with AWS and Kubernetes to join our team. The ideal candidate should have strong experience with infrastructure as code (e.g., Terraform, CloudFormation), CI/CD pipelines, and containerization technologies. Proficiency in scripting languages such as Python or Bash is required. You'll be responsible for maintaining and improving our cloud infrastructure, automating deployment processes, and ensuring high availability and scalability of our services. Experience with monitoring tools (e.g., Prometheus, Grafana) and log management solutions is highly desirable.",
                            Title = "DevOps Engineer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "We're hiring a UX Designer with 2+ years of experience in creating user-centered designs for web and mobile applications. The ideal candidate should have a strong portfolio demonstrating their ability to conduct user research, create wireframes, prototypes, and high-fidelity mockups. Proficiency in design tools such as Figma, Sketch, or Adobe XD is required. Experience with design systems, accessibility standards, and conducting usability testing is highly valued. You'll work closely with product managers, developers, and stakeholders to create intuitive and visually appealing user experiences.",
                            Title = "UX Designer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
